version: '3.8'
services:
  node1:
    image: 'docker.io/bitnami/mariadb-galera:10.5-debian-10'
    ports:
      - '3306:3306'
      - '4444:4444'
      - '4567:4567'
      - '4568:4568'
    volumes:
      - 'mariadb_galera_data:/bitnami/mariadb1'
    environment:
      - BITNAMI_DEBUG=false
      - MARIADB_GALERA_MARIABACKUP_PASSWORD=secret
      - MARIADB_USER=maria
      - MARIADB_ROOT_USER=root
      - MARIADB_PASSWORD=secret
      - MARIADB_ROOT_PASSWORD=secret
      - CLUSTER_NAME=integration-mariadb
      - CLUSTER_ADDRESS=gcomm://
    command: /opt/bitnami/scripts/mariadb-galera/entrypoint.sh /opt/bitnami/scripts/mariadb-galera/run.sh
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb-galera/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6
  node2:
    image: 'docker.io/bitnami/mariadb-galera:10.5-debian-10'
    volumes:
      - 'mariadb_galera_data:/bitnami/mariadb2'
    environment:
      - BITNAMI_DEBUG=false
      - MARIADB_GALERA_MARIABACKUP_PASSWORD=secret
      - MARIADB_USER=maria
      - MARIADB_ROOT_USER=root
      - MARIADB_PASSWORD=secret
      - MARIADB_ROOT_PASSWORD=secret
      - CLUSTER_NAME=integration-mariadb
      - CLUSTER_ADDRESS=gcomm://
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb-galera/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6
  node3:
    image: 'docker.io/bitnami/mariadb-galera:10.5-debian-10'
    volumes:
      - 'mariadb_galera_data:/bitnami/mariadb3'
    environment:
      - BITNAMI_DEBUG=false
      - MARIADB_GALERA_MARIABACKUP_PASSWORD=secret
      - MARIADB_USER=maria
      - MARIADB_ROOT_USER=root
      - MARIADB_PASSWORD=secret
      - MARIADB_ROOT_PASSWORD=secret
      - CLUSTER_NAME=integration-mariadb
      - CLUSTER_ADDRESS=gcomm://
    healthcheck:
      test: [ 'CMD', '/opt/bitnami/scripts/mariadb-galera/healthcheck.sh' ]
      interval: 15s
      timeout: 5s
      retries: 6

volumes:
  mariadb_galera_data:
    driver: local
