name: build-and-test
on: [push, pull_request]
jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install cargo
        uses: actions-rs/cargo@v1
        with:
          command: build
